import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { Toaster } from "@/components/ui/sonner";
import TanstackProvider from "@/providers/TanstackProvider";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "User Task Management System",
  description: "Generated by Sandun",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={inter.className}>
          <TanstackProvider>
            <Toaster />
            {children}
          </TanstackProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
